dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

name: insuguia_mobile
description: Aplicativo Flutter para apoio à prescrição de insulina hospitalar.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

flutter:
  uses-material-design: true
